---
- name: Copy files to multiple server
  hosts: all
  become: true 

  tasks: 
   - name: Copy files from source to destination
     copy: 
      src: /tmp/test/test2
      dest: /home/nadda/ 
      remote_src: yes
