---
- name: Copy files to multiple server
  hosts: all
  become: true 

  tasks: 
   - name: Copy files from source to destination
     copy: 
      src: /projects/files/
      dest: /home/nadda/ 
      
